### ISSUE TITLE
在有TableView和UIScrollView的ViewController里都不能用

### ISSUE THREAD

**Issue by songhailiang** [zhengwenming/ScreenShotBack#1]
当push后的ViewController里有UITableView或者UIScrollView时，这个就不好使了，这样的话可适用性就太小了吧

**Comment by zhengwenming** [comment]
1、首先感谢您的使用。
2、有bug或者不足之处,可以把小demo发至我的私人邮箱，我尽力修改。谢谢。740747055@qq.com
