### ISSUE TITLE
功能待完善的地方 求完善

### ISSUE THREAD

**Issue by iYeso** [zhengwenming/ScreenShotBack#10]
如果当前的视图是tableView视图 在全屏返回手势的时候  可以上下拖动tableView， 我不想要这种效果 想做类似今日头条的效果，  在全屏返回拖动期间 当前的控制的如果包含tableView是不允许上下拖动的， 现在咱们的框架存在这个问题

**Comment by SmallTwoInn** [comment]
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    
    NSLog(@"shouldRecognizeSimultaneouslyWithGestureRecognizer---%@", otherGestureRecognizer);
    if ([otherGestureRecognizer isKindOfClass:NSClassFromString(@"UIScrollViewPanGestureRecognizer")] || [otherGestureRecognizer isKindOfClass:NSClassFromString(@"UIPanGestureRecognizer")]|| [otherGestureRecognizer isKindOfClass:NSClassFromString(@"UIScrollViewPagingSwipeGestureRecognizer")]){
        //冲突要有两个，二者不可兼得
        UIView *aView = otherGestureRecognizer.view;
        if ([aView isKindOfClass:[UIScrollView class]] && [otherGestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]]) {
            UIScrollView *sv = (UIScrollView *)aView;
            CGFloat svWidth = sv.contentSize.width;
            NSInteger subViewsNum = svWidth/[UIScreen mainScreen].bounds.size.width;
            
            UIPanGestureRecognizer *panGest = (UIPanGestureRecognizer *)otherGestureRecognizer;
            CGPoint translation = [panGest translationInView:self.view];
            //设置左滑和右滑的情况
            // 右滑的情况
            if (translation.x > 0){
                // 如果是scrollView多视图  类似附近 广场 推荐的滚动
                if((sv.contentOffset.x==0) && (subViewsNum > 1) ){
                    return YES;
                }
            }else{
                // tableView的左滑
                if ((sv.contentOffset.x==0) && (subViewsNum == 1)){
                    return YES;
                }
            }
        }
    }
    return NO;
}

**Comment by zhengwenming** [comment]
在手势代理中添加一个if判断即可，放到判断UIScrollVIew之前

if ([sv isKindOfClass:UITableView.class]) {
                return YES;
            }
