### ISSUE TITLE
在iPhone6 上右滑值320 写死固定 动画后面有点不流畅 

### ISSUE THREAD

**Issue by ruanjunhao** [zhengwenming/ScreenShotBack#4]
你好  在iPhone6 上右滑值320 写死固定 动画后面有点不流畅 写成 rootVC.view.transform = CGAffineTransformMakeTranslation(rootVC.view.frame.size.width, 0);  改成屏幕宽度 但是滑动结束后 要展示的界面会有一个小的抖动的效果  不知道怎么解决哦 

CGPoint point_inView = [panGesture translationInView:self.view];
        if (point_inView.x >= DISTANCE_TO_POP)
        {
            [UIView animateWithDuration:0.3 animations:^{
                rootVC.view.transform = CGAffineTransformMakeTranslation(320, 0);
                presentedVC.view.transform = CGAffineTransformMakeTranslation(320, 0);

**Comment by zhengwenming** [comment]
为什么要写死 320？

**Comment by zhengwenming** [comment]
已经私下解决了，这里是因为改了一处为320，其他的没改。正确的做法是要改，全部都改为320，就不会有bug了。
