### ISSUE TITLE
KVO导致崩溃,每次在切换登录控制器和主窗口时总会崩溃

### ISSUE THREAD

**Issue by phasewong** [zhengwenming/ScreenShotBack#5]
接入您的截屏返回,但是每次在登录控制器输入用户名和密码登录后崩溃,报错如下:
'NSInternalInconsistencyException', reason: 'An instance 0x7fdc5b708a20 of class UIView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x618000032e20> (
<NSKeyValueObservance 0x618000050aa0: Observer: 0x7fdc5b7099f0, Key path: transform, Options: <New: YES, Old: NO, Prior: NO> Context: 0x106150410, Property: 0x618000050ad0>

**Comment by zhengwenming** [comment]
项目结构问题，这个是因为你观察的view释放了，但是你没有移除kvo。继续观察一个不存在的（释放了）对象，肯定崩溃。
你需要修改一下，保证你观察的对象不会释放。

如果你不知道怎么修改，可以写个崩溃的demo给我，我免费给你修改。发给我邮箱就可以了740747055@qq.ocm

**Comment by phasewong** [comment]
感谢大神,上面的问题已经解决,但现在又碰到新的问题:项目中有退出按钮时,比如在您的demo中ColumnViewController中加入一个退出的按钮,项目需求是点击退出按钮,重新设置rootViewController为UserGuiderViewController,但是进入引导页点击立即体验会蹦:reason: 'An instance 0x7f9529c047e0 of class UILayoutContainerView was deallocated while key value observers were still registered with it;
如果退出按钮是以modal形式进入UserGuiderViewController,那么进入引导页点击立即体验后进入首页 所有返回手势截图也不对
#pragma mark - 退出按钮点击
- (void)exitBtnClick{
//            [UIApplication sharedApplication].keyWindow.rootViewController = [[UserGuiderViewController alloc]init];
    [self presentViewController:[[UserGuiderViewController alloc]init] animated:YES completion:nil];
}

**Comment by zhengwenming** [comment]
这是KVO的基本用法，你重新设置rootViewController,就是相当于释放了之前的rootVC，那么你是不是要把kvo的观察者给remove掉呢？

**Comment by phasewong** [comment]
那我重新设置rootVC的时候需要将原来的screenshotView销毁后再重新创建一个screenshotView吗?

**Comment by zhengwenming** [comment]
我看了你发给我的demo，你还是没有remove掉kvo。

不过代码都都完善好了，demo我已经帮你改好了，demo发到你的邮箱里面了。
再次感谢你的使用和提出的bug。

**Comment by LvChao0608** [comment]
之前看到苏宁原码里面有这个效果，代码和你的差不多呢
