### ISSUE TITLE
由于某种原因，我需要编译成.a库，所以在方法screenShot里是否可以这样修改：

### ISSUE THREAD

**Issue by hegelsu** [zhengwenming/ScreenShotBack#8]
[[UIApplication sharedApplication].windows[[UIApplication sharedApplication].windows.count-1]
或者：
[[UIApplication sharedApplication].windows[0]

**Comment by hegelsu** [comment]
当然第一步第二步，第三步肯定也会做，个人感觉[[UIApplication sharedApplication].windows[0]用这个是对的

或者直接换成下面的这个也是可以的吧：
[self.superview.layer renderInContext:UIGraphicsGetCurrentContext()];

**Comment by zhengwenming** [comment]
1、不建议这么做--->[[UIApplication sharedApplication].windows[0]
因为这么去取数组中的第一个，不安全。鬼知道苹果会不会iOS12的时候改变了windows数组的结构呢。

2、建议用[self.superview.layer renderInContext:UIGraphicsGetCurrentContext()];
如果可以，那么建议用。

3、另外，代码是开源的，你可以随便修改，去适应你的项目需求。但是必须要测试几番。

**Comment by hegelsu** [comment]
好的，谢谢。
